services:
  nextjs:
    image: node:22-alpine
    container_name: nextjs_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
